[config]
# ...

[templates.hyprland]
input_path = '/home/dasam/.config/matugen/templates/hyprland-colors.conf'
output_path = '/home/dasam/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '/home/dasam/.config/matugen/templates/colors.css'
output_path = '/home/dasam/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.rofi]
input_path = '/home/dasam/.config/matugen/templates/rofi-color.rasi'
output_path = '/home/dasam/.config/rofi/colors.rasi'

[templates.kitty]
input_path = '/home/dasam/.config/matugen/templates/kitty-colors.conf'
output_path = '/home/dasam/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

