general {
    lock_cmd = pidof hyprlock || hyprlock       # blokuj ekran
    before_sleep_cmd = loginctl lock-session    # blokuj przed uśpieniem
    after_sleep_cmd = hyprctl dispatch dpms on  # włącz ekran po wybudzeniu
}

listener {
    timeout = 900                                # 15 minut → zablokuj ekran
    on-timeout = loginctl lock-session
}

listener {
    timeout = 960                                # 16 minut → wyłącz monitor
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
