general {
    lock_cmd = pidof hyprlock || hyprlock       # co wywołać przy blokowaniu
    before_sleep_cmd = loginctl lock-session    # blokuj przed uśpieniem komputera
    after_sleep_cmd = hyprctl dispatch dpms on  # włącz ekran po wybudzeniu
}

listener {
    timeout = 1200                                # czas w sekundach (tu 5 minut)
    on-timeout = loginctl lock-session           # zablokuj ekran
}

listener {
    timeout = 330                                # 30 sekund po zablokowaniu
    on-timeout = hyprctl dispatch dpms off       # wyłącz monitor, żeby oszczędzać prąd
    on-resume = hyprctl dispatch dpms on         # włącz monitor po ruchu myszką
}
